spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: shop_user
    password: shop_user
    url: "jdbc:mysql://localhost:3306/shop_product?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"
  application:
    name: product-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
